### ISSUE TITLE
Question about model

### ISSUE THREAD

**Issue by Dylan-Jinx** [JaehaKim97/Adaptive-Downsampling-Model#2]
hello @JaehaKim97 ,I want to talk about some question about the model.Can the model convert high resolution images to low resolution adaptively?

**Comment by JaehaKim97** [comment]
Yes, it is.

To be specific, our model aims to find the down-sampling kernel of a given arbitrary low-resolution image set.

**Comment by Dylan-Jinx** [comment]
I don't know if I have free time. I would like to have an online meeting to communicate with you. I think I may have encountered some problems or misunderstandings.

**Comment by Dylan-Jinx** [comment]
@JaehaKim97 ,I don't know if I have free time. I would like to have an online meeting to communicate with you. I think I may have encountered some problems or misunderstandings.

**Comment by JaehaKim97** [comment]
Could you please inform me of the problem you encounter? (e.g., data configuration, command, error message)

I can help you if I know the exact situation.

**Comment by Dylan-Jinx** [comment]
I read your paper and your readme of repository，and then I download DIV2K datasets. I choose X2 of DIV2k and put the datasets to named datasets of folder.finally I run this command ("python train.py --source DIV2k_train_HR --target X2 --name result --make_down”).The project structure like this picture
<img width="264" alt="图片" src="https://user-images.githubusercontent.com/57589991/219565438-654479d4-a3e3-49db-9bd7-c871db4036f9.png">
and error message like this
![图片](https://user-images.githubusercontent.com/57589991/219568354-deb9a7be-4534-4590-8b9b-280a793bba75.png)

**Comment by JaehaKim97** [comment]
I guess binary files are not properly generated.

1) Could you check that .png image files are located correctly in `datasets/X2/`? (It should not be in the directory form.)

2) Remove the `datasets/bin/X2/` file, and please run the command again.

**Comment by Dylan-Jinx** [comment]
I check that the `datasets/X2/` structure and rerun the command, it still occur the same error message.  I don't know what you put this data when your running this model success and when I want to use HR images change to LR images what should I do?

**Comment by Dylan-Jinx** [comment]
I think the primary problem binary files can not properly generated,could you tell me how to correctly put the dataset and run command?

**Comment by Dylan-Jinx** [comment]
@JaehaKim97 ,Thanks for your patient answer, it is the missing path slash that prevents the file from being read.The correctly run command is `python train.py --source DIV2K_train_HR/ --target X2/ ` attention the path slash.
